spring:
  application:
    name: springboot-elasticsearch
  data:
    elasticsearch:
      uris: http://locahost:9200

server:
  port: 8085
  servlet:
    context-path: /spelasticsearch

data:
  access:
    strategy: elasticSearchTemplate
